name: ErikTrefzger
favicon: null
layout_spectrum: 0.9639314305968583
typography_spectrum: 0.8596879253163934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2987624406814575
  lightness: 0.7320296370889992
  saturation: 0.4955784734338522
  rhythmicContrast: 0.41776891611516476
purpose: []
